<?php

$social_list = array(
	'500px'								=> '500px',
	'baidu-tieba'					=> 'Baidu Tieba',
	'behance'							=> 'Behance',
	'cloudapp'						=> 'CloudApp',
	'deviantart'					=> 'DeviantArt',
	'dribbble'						=> 'Dribbble',
	'dribble'							=> 'Dribble',
	'ello'								=> 'Ello',
	'envato'							=> 'Envato',
	'facebook-messanger'	=> 'Facebook Messanger',
	'facebook'						=> 'Facebook',
	'flikr'								=> 'Flikr',
	'github'							=> 'GitHub',
	'google-hangouts'			=> 'Google Hangouts',
	'google-map'					=> 'Google Map',
	'hype-machine'				=> 'Hype Machine',
	'instagram'						=> 'Instagram',
	'kickstarter'					=> 'KickStarter',
	'linkedin'						=> 'LinkedIn',
	'meetup'							=> 'MeetUp',
	'pinterest'						=> 'Pinterest',
	'reddit'							=> 'Reddit',
	'rss'									=> 'RSS',
	'shopify'							=> 'Shopify',
	'skype'								=> 'Skype',
	'slack'								=> 'Slack',
	'slidshare'						=> 'Slideshare',
	'smugmug'							=> 'Smugmug',
	'snapchat'						=> 'Snapchat',
	'soundcloud'					=> 'SoundCloud',
	'spotify'							=> 'Spotify',
	'stack-exchange'			=> 'Stack Exchange',
	'stack-overflow'			=> 'Stack Overflow',
	'steam'								=> 'Steam',
	'telegram'						=> 'Telegram',
	'trello'							=> 'Trello',
	'tumblr'							=> 'Tumblr',
	'twitch'							=> 'Twitch',
	'twitter'							=> 'Twitter',
	'viber'								=> 'Viber',
	'vimeo'								=> 'Vimeo',
	'vk'									=> 'VK',
	'whatsapp'						=> 'WhatsApp',
	'youtube'							=> 'YouTube',
);

?>
