<?php

$animate_css_list = array(
	'bounce'							=> esc_html__('Bounce', 'kirki'),
	'flash'								=> esc_html__('Flash', 'kirki'),
	'pulse'								=> esc_html__('Pulse', 'kirki'),
	'rubberBand'					=> esc_html__('Rubber Band', 'kirki'),
	'shake'								=> esc_html__('Shake', 'kirki'),
	'swing'								=> esc_html__('Swing', 'kirki'),
	'tada'								=> esc_html__('Tada', 'kirki'),
	'wobble'							=> esc_html__('Wobble', 'kirki'),
	'jello'								=> esc_html__('Jello', 'kirki'),
	'heartBeat'						=> esc_html__('Heart Beat', 'kirki'),
	'bounceIn'						=> esc_html__('Bounce In', 'kirki'),
	'bounceInDown'				=> esc_html__('Bounce In Down', 'kirki'),
	'bounceInLeft'				=> esc_html__('Bounce In Left', 'kirki'),
	'bounceInRight'				=> esc_html__('Bounce In Right', 'kirki'),
	'bounceInUp'					=> esc_html__('Bounce In Up', 'kirki'),
	'fadeIn'							=> esc_html__('Fade In', 'kirki'),
	'fadeInDown'					=> esc_html__('Fade In Down', 'kirki'),
	'fadeInDownBig'				=> esc_html__('Fade In Down Big', 'kirki'),
	'fadeInLeft'					=> esc_html__('Fade In Left', 'kirki'),
	'fadeInLeftBig'				=> esc_html__('Fade In Left Big', 'kirki'),
	'fadeInRight'					=> esc_html__('Fade In Right', 'kirki'),
	'fadeInRightBig'			=> esc_html__('Fade In Right Big', 'kirki'),
	'fadeInUp'						=> esc_html__('Fade In Up', 'kirki'),
	'fadeInUpBig'					=> esc_html__('Fade In Up Big', 'kirki'),
	'flip'								=> esc_html__('Flip', 'kirki'),
	'flipInX'							=> esc_html__('Flip In X', 'kirki'),
	'flipInY'							=> esc_html__('Flip In Y', 'kirki'),
	'lightSpeedIn'				=> esc_html__('Lightspeed', 'kirki'),
	'rotateIn'						=> esc_html__('Rotate In', 'kirki'),
	'rotateInDownLeft'		=> esc_html__('Rotate In Down Left', 'kirki'),
	'rotateInDownRight'		=> esc_html__('Rotate In Down Right', 'kirki'),
	'rotateInUpLeft'			=> esc_html__('Rotate In Up Left', 'kirki'),
	'rotateInUpRight'			=> esc_html__('Rotate In Up Right', 'kirki'),
	'slideInDown'					=> esc_html__('Slide In Down', 'kirki'),
	'slideInLeft'					=> esc_html__('Slide In Left', 'kirki'),
	'slideInRight'				=> esc_html__('Slide In Right', 'kirki'),
	'slideInUp'						=> esc_html__('Slide In Up', 'kirki'),
	'zoomIn'							=> esc_html__('Zoom In', 'kirki'),
	'zoomInDown'					=> esc_html__('Zoom In Down', 'kirki'),
	'zoomInLeft'					=> esc_html__('Zoom In Left', 'kirki'),
	'zoomInRight'					=> esc_html__('Zoom In Right', 'kirki'),
	'zoomInUp'						=> esc_html__('Zoom In Up', 'kirki'),
	'jackInTheBox'				=> esc_html__('Jack In The Box', 'kirki'),
	'rollIn'							=> esc_html__('Roll In', 'kirki'),
);

?>
