<?php

Kirki::add_section('presets_section', array(
	'title'       => esc_html__('Theme Presets', 'planeta'),
	'priority'		=> 1,
));

Kirki::add_field('planeta_config', array(
	'type'					=> 'select',
	'label'					=> esc_html__('Content Preset/Layout', 'planeta'),
	'settings'			=> 'content_preset',
	'section'				=> 'presets_section',
	'default'				=> 'none',
	'choices'				=> array(
		'none'					=> esc_html__('None (default)', 'planeta'),
		'informal'			=> esc_html__('Informal', 'planeta'),
	),
	'preset'      	=> array(
		'informal'    		=> array(
			'settings' 				=> array(
				//Section Layouts
				'sections_layout'												=> array(
					'client',
					'generic-1',
					'project',
					'testimonial',
					'number',
					'service',
					'tech',
					'team',
					'contact',
					'post',
				),
				'client_title'													=> get_theme_mod('client_title', esc_html__('As adults, we are told not to ask questions. Here we can.', 'planeta')),
				'client_subtitle'												=> get_theme_mod('client_subtitle', ''),
				'client_items_spacing_between'					=> 15,
				'client_name'														=> '',
				'generic-1_title'												=> get_theme_mod('generic-1_title', esc_html__('We are Tilda Center', 'planeta')),
				'generic-1_subtitle'										=> get_theme_mod('generic-1_subtitle', esc_html__('We are a hackerspace from Novi Sad, Serbia. Simply put - if you are a hacker, troll, alien, or just normal human tying to learn new things, this is the place for you!', 'planeta')),
				'generic-1_name'												=> get_theme_mod('generic-1_name', esc_html__('Who We Are?', 'planeta')),
				'project_title'													=> get_theme_mod('project_title', esc_html__('Some things we did...', 'planeta')),
				'project_subtitle'											=> get_theme_mod('project_subtitle', ''),
				'testimonial_title'											=> get_theme_mod('testimonial_title', esc_html__('What they have said?', 'planeta')),
				'testimonial_subtitle'									=> get_theme_mod('testimonial_subtitle', ''),
				'testimonial_name'											=> get_theme_mod('testimonial_name', esc_html__('Testimonials', 'planeta')),
				'number_title'													=> get_theme_mod('number_title', esc_html__('Not to brag, but...', 'planeta')),
				'number_subtitle'												=> get_theme_mod('number_subtitle', ''),
				'number_name'														=> get_theme_mod('number_name', esc_html__('Numbers', 'planeta')),
				'service_title'													=> get_theme_mod('service_title', esc_html__('Some services that you might find useful...', 'planeta')),
				'service_subtitle'											=> get_theme_mod('service_subtitle', ''),
				'service_name'													=> get_theme_mod('service_name', esc_html__('Services', 'planeta')),
				'tech_title'														=> get_theme_mod('tech_title', esc_html__('Recognize any of these?', 'planeta')),
				'tech_subtitle'													=> get_theme_mod('tech_subtitle', esc_html__('We use them all!', 'planeta')),
				'tech_layout'														=> array(
					'title',
					'items',
					'subtitle',
				),
				'tech_name'															=> get_theme_mod('tech_name', esc_html__('Tech Stack', 'planeta')),
				'team_title'														=> get_theme_mod('team_title', esc_html__('The Crazy Ones', 'planeta')),
				'team_subtitle'													=> get_theme_mod('team_subtitle', ''),
				'team_name'															=> get_theme_mod('team_name', esc_html__('Team', 'planeta')),
				'contact_title'													=> get_theme_mod('contact_title', esc_html__('Drop us a message', 'planeta')),
				'contact_subtitle'											=> get_theme_mod('contact_subtitle', ''),
				'contact_name'													=> get_theme_mod('contact_name', esc_html__('Contact Us', 'planeta')),
				'post_title'														=> get_theme_mod('post_title', esc_html__('What we wrote lately?', 'planeta')),
				'post_subtitle'													=> get_theme_mod('post_subtitle', ''),
				'post_name'															=> get_theme_mod('post_name', esc_html__('Posts', 'planeta')),

			),
		),
	),
));

Kirki::add_field('planeta_config', array(
	'type'					=> 'select',
	'label'					=> esc_html__('Color Scheme, Typography and Effects', 'planeta'),
	'settings'			=> 'color_scheme',
	'section'				=> 'presets_section',
	'default'				=> 'none',
	'choices'				=> array(
		'none'						=> esc_html__('None (default)', 'planeta'),
		'retrowave-dark'	=> esc_html__('Retrowave Dark (Pink)', 'planeta'),
	),
	'preset'      	=> array(
		'retrowave-dark' 	=> array(
			'settings' 				=> array(

				//General
				'primary_color_enable'									=> true,
				'primary_color'													=> '#FF2795',
				'global_background'											=> array(
					'background-color'											=> '#212121',
					'background-image'											=> '',
				),
				'container_default'											=> 1200,
				'container_article'											=> 700,
				'loading_enable'												=> true,
				'loading_background'										=> '#212121',
				'page_title_background'									=> '#FF2795',
				'navbar_padding'												=> 112,
				'menu_background'												=> array(
					'background-color'											=> '#212121',
					'background-image'											=> '',
				),
				'hamburger_sharp'												=> true,
				'scroll_down_bottom'										=> 110,

				//Sections
				'team_masonry_num'											=> '4',
				'team_enable_masonry'										=> false,
				'service_masonry_num'										=> '2',
				'service_enable_masonry'								=> false,
				'number_masonry_num'										=> '4',
				'number_enable_masonry'									=> false,
				'project_masonry_num'										=> '2',
				'project_enable_masonry'								=> true,
				'post_masonry_num'											=> '2',
				'post_enable_masonry'										=> true,
				'testimonial_masonry_num'								=> '2',
				'testimonial_enable_masonry'						=> true,

				//Typography
				'typography_main_color'									=> '#FFFFFF',
				'typography_main_fluid'									=> true,
				'typography_main_fluid_size'						=> '21',
				'typography_button_link_hover'					=> 'box-2',
				'typography_button_link_border_size'		=> 2,
				'typography_button_link_inherit_typography' => true,
				'typography_section_title_inherit_size'	=> true,
				'typography_section_title_inherit_typography' => false,
				'typography_section_title'							=> array(
					'text-transform'			=> 'none',
					'color'								=> '#FFFFFF',
					'font-family'					=> 'inherit',
					'variant'							=> 'regular',
					'line-height'					=> '1.5',
					'letter-spacing'			=> '0',
					'text-align'					=> 'center',
				),
				'typography_section_subtitle_inherit_size'	=> false,
				'typography_section_subtitle_inherit_typography'=> false,
				'typography_section_subtitle'						=> array(
					'text-transform'			=> 'none',
					'color'								=> '#FFFFFF',
					'font-family'					=> 'inherit',
					'variant'							=> 'regular',
					'line-height'					=> '1.5',
					'letter-spacing'			=> '0',
					'text-align'					=> 'center',
				),
				'typography_section_subtitle_size'			=> 1.2,
				'typography_page_title_inherit_size'		=> true,
				'typography_page_title_inherit_typography' => false,
				'typography_page_title'									=> array(
					'text-transform'			=> 'none',
					'color'								=> '#FFFFFF',
					'font-family'					=> 'inherit',
					'variant'							=> 'regular',
					'line-height'					=> '1.5',
					'letter-spacing'			=> '0',
					'text-align'					=> 'center',
				),

				//Animations
				'section_title_trigger'									=> 'lax',
				'section_title_lax_type_1'							=> 'zoomIn',
				'section_title_strength_zoomIn_1'				=> 0.85,
				'section_title_lax_type_2'							=> 'zoomOut',
				'section_title_strength_zoomOut_2'			=> 0.85,
				'section_title_lax_type_3'							=> 'none',
				'section_subtitle_trigger'							=> 'lax',
				'section_subtitle_lax_type_1'						=> 'zoomIn',
				'section_subtitle_strength_zoomIn_1'		=> 0.85,
				'section_subtitle_lax_type_2'						=> 'zoomOut',
				'section_subtitle_strength_zoomOut_2'		=> 0.85,
				'section_subtitle_lax_type_3'						=> 'none',
				'section_logo_trigger'									=> 'lax',
				'section_logo_lax_type_1'								=> 'zoomIn',
				'section_logo_strength_zoomIn_1'				=> 0.85,
				'section_logo_lax_type_2'								=> 'zoomOut',
				'section_logo_strength_zoomOut_2'				=> 0.85,
				'section_logo_lax_type_3'								=> 'none',
				'page_title_trigger'										=> 'lax',
				'page_title_lax_type_1'									=> 'zoomIn',
				'page_title_strength_zoomIn_1'					=> 0.85,
				'page_title_lax_type_2'									=> 'zoomOut',
				'page_title_strength_zoomOut_2'					=> 0.85,
				'page_title_lax_type_3'									=> 'none',
				'card_image_trigger'										=> 'lax',
				'card_image_lax_type_1'									=> 'zoomIn',
				'card_image_strength_zoomIn_1'					=> 0.85,
				'card_image_lax_type_2'									=> 'zoomOut',
				'card_image_strength_zoomOut_2'					=> 0.85,
				'card_image_lax_type_3'									=> 'none',
				'card_info_trigger'											=> 'lax',
				'card_info_lax_type_1'									=> 'zoomIn',
				'card_info_strength_zoomIn_1'						=> 0.85,
				'card_info_lax_type_2'									=> 'zoomOut',
				'card_info_strength_zoomOut_2'					=> 0.85,
				'card_info_lax_type_3'									=> 'none',
			),
		),
	),
));

?>
