<?php

Kirki::add_section('presets_section', array(
	'title'       => esc_html__('Theme Presets', 'planeta'),
	'priority'		=> 1,
));

Kirki::add_field('planeta_config', array(
	'type'					=> 'select',
	'label'					=> esc_html__('Theme Preset', 'planeta'),
	'settings'			=> 'effects_scheme',
	'section'				=> 'presets_section',
	'default'				=> 'none',
	'choices'				=> array(
		'none'						=> esc_html__('None (default)', 'planeta'),
		'portfolio'				=> esc_html__('Agency/Personal Portfolio', 'planeta'),
		'software'				=> esc_html__('Software Company', 'planeta'),
		'freelancer'			=> esc_html__('Freelancer', 'planeta'),
	),
	'preset'      	=> array(
		'software' 				=> array(
			'settings' 					=> array(
				//Section Layouts
				'sections_layout'										=> array(
					'client',
					'generic-1',
					'project',
					'testimonial',
					'number',
					'service',
					'tech',
					'team',
					'contact',
					'post',
				),
				'client_title'											=> get_theme_mod('client_title', esc_html__('As adults, we are told not to ask questions. Here we can.', 'planeta')),
				'client_subtitle'										=> get_theme_mod('client_subtitle', ''),
				'client_items_spacing_between'			=> 15,
				'client_name'												=> '',
				'generic-1_title'										=> get_theme_mod('generic-1_title', esc_html__('We are Planeta', 'planeta')),
				'generic-1_subtitle'								=> get_theme_mod('generic-1_subtitle', esc_html__("We are a team of experts located in Novi Sad, Serbia. We are learders in making the world's software - awesome", 'planeta')),
				'generic-1_name'										=> get_theme_mod('generic-1_name', esc_html__('Who We Are?', 'planeta')),
				'project_title'											=> get_theme_mod('project_title', esc_html__('Some things we did...', 'planeta')),
				'project_subtitle'									=> get_theme_mod('project_subtitle', ''),
				'project_name'											=> get_theme_mod('project_name', esc_html__('Projects', 'planeta')),
				'testimonial_title'									=> get_theme_mod('testimonial_title', esc_html__('What they have said?', 'planeta')),
				'testimonial_subtitle'							=> get_theme_mod('testimonial_subtitle', ''),
				'testimonial_name'									=> get_theme_mod('testimonial_name', esc_html__('Testimonials', 'planeta')),
				'number_title'											=> get_theme_mod('number_title', esc_html__('Not to brag, but...', 'planeta')),
				'number_subtitle'										=> get_theme_mod('number_subtitle', ''),
				'number_name'												=> get_theme_mod('number_name', esc_html__('Numbers', 'planeta')),
				'service_title'											=> get_theme_mod('service_title', esc_html__('Some services that you might find useful...', 'planeta')),
				'service_subtitle'									=> get_theme_mod('service_subtitle', ''),
				'service_name'											=> get_theme_mod('service_name', esc_html__('Services', 'planeta')),
				'tech_title'												=> get_theme_mod('tech_title', esc_html__('Recognize any of these?', 'planeta')),
				'tech_subtitle'											=> get_theme_mod('tech_subtitle', esc_html__('We use them all!', 'planeta')),
				'tech_layout'												=> array(
					'title',
					'items',
					'subtitle',
				),
				'tech_name'													=> get_theme_mod('tech_name', esc_html__('Tech Stack', 'planeta')),
				'team_title'												=> get_theme_mod('team_title', esc_html__('The Crazy Ones', 'planeta')),
				'team_subtitle'											=> get_theme_mod('team_subtitle', ''),
				'team_name'													=> get_theme_mod('team_name', esc_html__('Team', 'planeta')),
				'contact_title'											=> get_theme_mod('contact_title', esc_html__('Drop us a message', 'planeta')),
				'contact_subtitle'									=> get_theme_mod('contact_subtitle', ''),
				'contact_name'											=> get_theme_mod('contact_name', esc_html__('Contact Us', 'planeta')),
				'post_title'												=> get_theme_mod('post_title', esc_html__('What we wrote lately?', 'planeta')),
				'post_subtitle'											=> get_theme_mod('post_subtitle', ''),
				'post_name'													=> get_theme_mod('post_name', esc_html__('Posts', 'planeta')),

				//Section Items
				'team_masonry_num'									=> '4',
				'team_enable_masonry'								=> false,
				'service_masonry_num'								=> '2',
				'service_enable_masonry'						=> false,
				'number_masonry_num'								=> '4',
				'number_enable_masonry'							=> false,
				'project_masonry_num'								=> '2',
				'project_enable_masonry'						=> true,
				'project_image_shape'								=> 'none',
				'post_masonry_num'									=> '2',
				'post_enable_masonry'								=> false,
				'post_image_shape'									=> 'none',
				'testimonial_masonry_num'						=> '2',
				'testimonial_enable_masonry'				=> true,
				'contact_container_spacing_top'			=> 15,
				'contact_container_spacing_bottom'	=> 15,

				//Animations
				'section_title_anims_trigger'									=> 'lax',
				'section_title_anims_lax_type_1'							=> 'zoomInOut',
				'section_title_anims_strength_zoomInOut_1'		=> 0.85,
				'section_title_anims_lax_type_2'							=> 'none',
				'section_title_anims_lax_type_3'							=> 'none',
				'section_subtitle_anims_trigger'							=> 'lax',
				'section_subtitle_anims_lax_type_1'						=> 'zoomInOut',
				'section_subtitle_anims_strength_zoomInOut_1'	=> 0.85,
				'section_subtitle_anims_lax_type_2'						=> 'none',
				'section_subtitle_anims_lax_type_3'						=> 'none',
				'section_logo_anims_trigger'									=> 'lax',
				'section_logo_anims_lax_type_1'								=> 'zoomInOut',
				'section_logo_anims_strength_zoomInOut_1'			=> 0.85,
				'section_logo_anims_lax_type_2'								=> 'none',
				'section_logo_anims_lax_type_3'								=> 'none',
				'page_title_anims_trigger'										=> 'lax',
				'page_title_anims_lax_type_1'									=> 'zoomInOut',
				'page_title_anims_strength_zoomInOut_1'				=> 0.85,
				'page_title_anims_lax_type_2'									=> 'none',
				'page_title_anims_lax_type_3'									=> 'none',
				'card_image_anims_trigger'										=> 'lax',
				'card_image_anims_lax_type_1'									=> 'zoomInOut',
				'card_image_anims_strength_zoomInOut_1'				=> 0.85,
				'card_image_anims_lax_type_2'									=> 'swing',
				'card_image_anims_strength_swing_2'						=> 12,
				'card_image_anims_lax_type_3'									=> 'none',
				'card_info_anims_trigger'											=> 'lax',
				'card_info_anims_lax_type_1'									=> 'zoomInOut',
				'card_info_anims_strength_zoomInOut_1'				=> 0.85,
				'card_info_anims_lax_type_2'									=> 'none',
				'card_info_anims_lax_type_3'									=> 'none',
			),
		),
		'portfolio' 				=> array(
			'settings' 					=> array(
				//Section Layouts
				'sections_layout'												=> array(
					'client',
					'project',
					'contact',
					'post',
				),
				'client_title'													=> get_theme_mod('client_title', esc_html__('As adults, we are told not to ask questions. Here we can.', 'planeta')),
				'client_subtitle'												=> get_theme_mod('client_subtitle', esc_html__("We are a team of experts located in Novi Sad, Serbia. We are learders in making the world's software - awesome", 'planeta')),
				'client_items_spacing_between'					=> 15,
				'client_name'														=> '',
				'project_title'													=> get_theme_mod('project_title',''),
				'project_subtitle'											=> get_theme_mod('project_subtitle', ''),
				'contact_title'													=> get_theme_mod('contact_title', esc_html__("Let's Get in Touch", 'planeta')),
				'contact_subtitle'											=> get_theme_mod('contact_subtitle', 'Send us a message and we will reach to you as soon as possible'),
				'contact_name'													=> get_theme_mod('contact_name', esc_html__('Contact Us', 'planeta')),
				'post_title'														=> get_theme_mod('post_title', esc_html__('Latest Posts', 'planeta')),
				'post_subtitle'													=> get_theme_mod('post_subtitle', ''),
				'post_name'															=> get_theme_mod('post_name', esc_html__('Posts', 'planeta')),

				//Section Items
				'project_masonry_num'										=> '2',
				'project_enable_masonry'								=> true,
				'project_image_shape'										=> 'circle-full',
				'project_image_strength'								=> '4',
				'post_masonry_num'											=> '2',
				'post_enable_masonry'										=> false,
				'post_image_shape'											=> 'circle-full',
				'post_image_strength'										=> '4',
				'contact_container_spacing_top'					=> 15,
				'contact_container_spacing_bottom'			=> 15,

				//Animations
				'section_title_anims_trigger'									=> 'lax',
				'section_title_anims_lax_type_1'							=> 'zoomInOut',
				'section_title_anims_strength_zoomInOut_1'		=> 0.65,
				'section_title_anims_lax_type_2'							=> 'none',
				'section_title_anims_lax_type_3'							=> 'none',
				'section_subtitle_anims_trigger'							=> 'lax',
				'section_subtitle_anims_lax_type_1'						=> 'zoomInOut',
				'section_subtitle_anims_strength_zoomInOut_1'	=> 0.65,
				'section_subtitle_anims_lax_type_2'						=> 'none',
				'section_subtitle_anims_lax_type_3'						=> 'none',
				'section_logo_anims_trigger'									=> 'lax',
				'section_logo_anims_lax_type_1'								=> 'zoomInOut',
				'section_logo_anims_strength_zoomInOut_1'			=> 0.65,
				'section_logo_anims_lax_type_2'								=> 'none',
				'section_logo_anims_lax_type_3'								=> 'none',
				'page_title_anims_trigger'										=> 'lax',
				'page_title_anims_lax_type_1'									=> 'zoomInOut',
				'page_title_anims_strength_zoomInOut_1'				=> 0.65,
				'page_title_anims_lax_type_2'									=> 'none',
				'page_title_anims_lax_type_3'									=> 'none',
				'card_image_anims_trigger'										=> 'lax',
				'card_image_anims_lax_type_1'									=> 'zoomInOut',
				'card_image_anims_strength_zoomInOut_1'				=> 0.65,
				'card_image_anims_lax_type_2'									=> 'none',
				'card_image_anims_lax_type_3'									=> 'none',
				'card_info_anims_trigger'											=> 'lax',
				'card_info_anims_lax_type_1'									=> 'zoomInOut',
				'card_info_anims_strength_zoomInOut_1'				=> 0.65,
				'card_info_anims_lax_type_2'									=> 'none',
				'card_info_anims_lax_type_3'									=> 'none',
			),
		),
		'freelancer' 				=> array(
			'settings' 					=> array(
				//Section Layouts
				'sections_layout'										=> array(
					'client',
					'service',
					'project',
					'contact',
					'post',
				),
				'client_title'											=> get_theme_mod('client_title', esc_html__('My name is Adam Sigma', 'planeta')),
				'client_subtitle'										=> get_theme_mod('client_subtitle', esc_html__("I'm web developer from Novi Sad, Serbia.", 'planeta')),
				'client_items_spacing_between'			=> 15,
				'client_name'												=> '',
				'service_title'											=> get_theme_mod('service_title', esc_html__('What I Do', 'planeta')),
				'service_subtitle'									=> get_theme_mod('service_subtitle', ''),
				'service_name'											=> get_theme_mod('service_name', esc_html__('My Services', 'planeta')),
				'project_title'											=> get_theme_mod('project_title', 'My Works'),
				'project_subtitle'									=> get_theme_mod('project_subtitle', ''),
				'contact_title'											=> get_theme_mod('contact_title', esc_html__("Let's Get in Touch", 'planeta')),
				'contact_subtitle'									=> get_theme_mod('contact_subtitle', 'Send me a message and I will reach to you as soon as possible'),
				'contact_name'											=> get_theme_mod('contact_name', esc_html__('Contact', 'planeta')),
				'post_title'												=> get_theme_mod('post_title', esc_html__("What's Up?", 'planeta')),
				'post_subtitle'											=> get_theme_mod('post_subtitle', ''),
				'post_name'													=> get_theme_mod('post_name', esc_html__('News', 'planeta')),

				//Section Items
				'service_masonry_num'								=> '3',
				'service_enable_masonry'						=> false,
				'service_image_shape'								=> 'none',
				'project_masonry_num'								=> '3',
				'project_enable_masonry'						=> false,
				'project_image_shape'								=> 'none',
				'project_container_spacing_top'			=> 15,
				'post_masonry_num'									=> '3',
				'post_enable_masonry'								=> false,
				'post_image_shape'									=> 'none',

				//Animations
				'section_title_anims_trigger'				=> 'none',
				'section_subtitle_anims_trigger'		=> 'none',
				'section_logo_anims_trigger'				=> 'none',
				'page_title_anims_trigger'					=> 'aos',
				'page_title_anims_aos_type'					=> 'fade-up',
				'card_image_anims_trigger'					=> 'aos',
				'card_image_anims_aos_type'					=> 'fade-up',
			),
		),
	),
));

require_once(get_template_directory() . '/inc/customizer/presets-color-scheme.php');

?>
